### PR TITLE
Correct Light And Vertex Texture

### PR DESCRIPTION
**Pull request by NasimiAsl**

### CODE REVIEW

**Comment by RaananW** [comment]
Hi, 
I think it would be better to change the namespace of the extension, as this is not a part of the framework.
Can you change it to BABYLONX ?

**Comment by NasimiAsl** [comment]
hi Raanna i Think Need make general Desition abut that 
i think this tools need to go in the framework but anyway i just care to share that with others 
thank 
Date: Fri, 25 Mar 2016 08:26:08 -0700

**Comment by RaananW** [comment]
It's great that this tool is shared (I personally find out awesome)! I just think that to reduce confusion with the users, the namespace should be something else. Also to keep framework features apart from extensions. That's why I suggest BABYLONX as a namespace, instead of BABYLON for extensions. Notice how no other extension is using the BABYLON namespace.

**Comment by NasimiAsl** [comment]
i agree with that anyway  my words means about ' general Desition' is  if we wanna make all extensions in BABYLONX Namespace i am ready to change it. so sorry about ask again i am ready to change it and  
i   start making documentation and samples i can commit that when i commit documentation. is that ok

**Comment by RaananW** [comment]
Documentation will be wonderful! Add it to the extensions section of the doc site.
Yes, I think that from now on all extensions will have BABYLONX as namespace. There are a few already, now there's one more :smile:

**Comment by NasimiAsl** [comment]
i try finish   in this week :)

**Comment by NasimiAsl** [comment]
RaananW  is that correct Change All BABYLON to BABYLONX?

**Comment by RaananW** [comment]
All Namespaces, yes. So technically, changing module BABYLON to module BABYLONX (and then referencing all internal Babylon objects with BABYLON) will work.

**Comment by NasimiAsl** [comment]
Ok RaananW
i wanna make a sample all created with Shader Builder too I make sample Folder for this ?

**Comment by RaananW** [comment]
If you can create the samples in the Playground, it would be really great. Then you can write documentation on the official documentation web page with links to the playground.
You can of course create a directory in your project with samples, but then people won't be able to play with them too much.

**Pull request merged**
