### PR TITLE
Update Babylonx.ShaderBuilder.ts

### PR DESCRIPTION
**Pull request by royibernthal**

### CODE REVIEW

**Comment by RaananW** [comment]
Thanks for the commit!
I think @NasimiAsl should be the one reviewing this, as it's his extension.

**Comment by royibernthal** [comment]
Hi, yeah it was meant for NasimiAsl, we're talking about it on the forum.
I'm still trying to figure out how to do Pull Requests on GitHub properly, sorry if this was not done right.

**Comment by RaananW** [comment]
The pull request looks perfectly fine, if this is what you meant to commit :-)

**Comment by NasimiAsl** [comment]
i can review this in next week and have some changes too so i commit this after 10 days 
i think you can make your wanted shaderBuilder Version and  i can look in that and add my changes too

**Comment by NasimiAsl** [comment]
thanks all

**Comment by NasimiAsl** [comment]
wait i fix it and pull request again

**Comment by royibernthal** [comment]
Raanan - great, yeah I was just experimenting with a light commit.

NasimiAsl - np, I'll try to do some more fixes until next week.

Do you want me to do the same pull request again? not sure I understand.

**Comment by NasimiAsl** [comment]
i look to Func and find this function can make string too
so if i change this to 
Func(fun: any): any {
            return fun(Shader.Me);
        }
// any : some times ShaderBuilder and some times String ( shader String )
is that change solve your problem?

**Comment by royibernthal** [comment]
I don't have a real problem with that, basically I can cast to ShaderBuilder on my side if I know that's what's returned.
Just for semantics, maybe you can consider doing 2 different functions for each return type (ShaderBuilder or String), with ShaderBuilder being the way I mentioned in the forum:

Func( fun: (me: ShaderBuilder) => void ): ShaderBuilder{
fun(Shader.Me);
return ShaderBuilder.Me;
}

That way the user won't have to take care of returning the me parameter passed to the function, and in addition rtpescript will recognize the ShaderBuilder type, which will be helpful when chaining functions.

Anyway, it's not a must, just a suggestion.

On the other hand, if you don't like this suggestion, perhaps you can do something like this:

Func( fun: (me: ShaderBuilder) => void ): ShaderBuilder | string {
return fun(Shader.Me);
}

The return type will still have to be checked by the user, but it'll hint him what he needs to check for.

**Comment by royibernthal** [comment]
Is there a reason I can't create my own branch for:
https://github.com/BabylonJS/Extensions/blob/master/ShaderBuilder/Babylonx.ShaderBuilder.ts
Do I maybe not have permission to do that?

I'd like to modify it online so my changes are always saved even after a pull request.

**Comment by RaananW** [comment]
You can branch and edit your own fork at https://github.com/royibernthal/Extensions, then you can create new pull requests or update this one.

**Comment by royibernthal** [comment]
Thanks, I'll give it a try.
I'd like to do some modifications on Func(), in which cases does it return a String?

**Pull request closed without merging**
