### PR TITLE
Adding GIF Exporting Feature 

### PR DESCRIPTION
**Pull request by antpowell**
Allow for recording of a Scene and exporting that recording as a GIF to the local machine.

### CODE REVIEW

**Comment by deltakosh** [comment]
Once merged, you will need to provide documentation on doc.babylonjs.com/extensions :)

Thanks a lot Anthony!

**Comment by antpowell** [comment]
Rgr that, will do.

**Comment by antpowell** [comment]
Will check that out right away.

**Comment by deltakosh** [comment]
I think dist should also contains the final file

**Comment by deltakosh** [comment]
Still no .js in dist, is it expected?

**Comment by antpowell** [comment]
I just found out why, the global .gitignore has *.js and *.map so all my commits where basically doing nothing, lol. should I remove that and rebuild?

**Comment by deltakosh** [comment]
You can manually add the specific files you need

**Comment by deltakosh** [comment]
Wonderful :D

**Comment by deltakosh** [comment]
Now we need a beautiful doc and we can start socializing your great work!

**Comment by deltakosh** [comment]
Can you check on the repo as well if all the files are required ? i saw file with 123456.js in dist that looks suspicious
Also there is a dist folder in the example folder

**Comment by sebavan** [comment]
great job with that !!!

**Comment by antpowell** [comment]
The 12345.js is the worker and the naming is how parcel bundled it but I can fix that, and same for the dist in the example I use parcel to run the server for testing and it creates a dist by default.

**Comment by deltakosh** [comment]
yes we need more meaningful naming ;)

**Pull request merged**
